name: Update villages
on:
  schedule:
  # from RELEASE POLARBEAR 1171.1, map.sql is updated every midnight server time
  # (which is 00:00 GMT+1 or 23:00 GMT)
  # we execute after 1 hour to make sure map.sql updated
    - cron:  00 00 * * *
  workflow_dispatch:
jobs:
  execute:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        world_url: 
          - ts8.x1.arabics.travian.com
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2        
      - name: Download build
        uses: robinraju/release-downloader@v1.7
        with:
          repository: "vinaghost/TravianMapSqlAnalytics"
          latest: true
          out-file-path: "release"
      - name: Extract
        run: |
          tar -xvf MapSqlDownloader.tar.gz
        working-directory: release
      - name: Run map.sql downloader
        run: |
          chmod +x ./MapSqlDownloader
          ./MapSqlDownloader ${{ matrix.world_url }}
        working-directory: release/MapSqlDownloader
      - name: Post Run map.sql downloader
        run: |
          cp -a release/MapSqlDownloader/${{ matrix.world_url }}/. .
          ls -R
